### PR TITLE
Time ranges

### LINKED ISSUE #140: Add time range dropdown in addition to time range controls.
LG request.

# Test notes
* A dropdown labeled _Time Range_ appears with two options by default: _full_ and _user input_.
* When `date_range`, `date_ranges`, `day_range`, or `day_ranges` are specified, a corresponding option should appear in the dropdown:
  * `{time_scale: 'date', date_range: ['2015-01-01', '2017-01-01']}`
  * `{time_scale: 'date', date_ranges: [{label: 'this is a date range', domain: ['2015-01-01', '2017-01-01']}]}`
  * `{time_scale: 'day', day_range: [0,400]}`
  * `{time_scale: 'day', day_ranges: [{label: 'this is a day range', domain: [0,400]}]}`
* When the _Time range_ _start_ or _end_ controls are changed the _Time range_ control should switch to _user input_.

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #140

### CODE REVIEW

**Comment by pburnsdata** [comment]
Lots of changes to get this one done - good job. Not sure what this failed check is? When I ran test I didn't have any problems, but could be misunderstanding the error the check message. Also, if I'm understanding it correctly, might want to add date_ranges and day_ranges with their explanations to the settings-schema.json.

**Comment by danedexF5** [comment]
@pburnsdata Ok so should I use lucky-charms to test this instead of time-ranges?

**Comment by danedexF5** [comment]
@samussiah tested in all 3. If "default" is what we want for the drop down option as mentioned below, then I think this is good. Also, I sued the lucky-charms branch to test this per Preston's notes.
- When I add the block {time_scale: 'date', date_range: ['2015-01-01', '2017-01-01']} the new option I get on the drop down is "default"
- When I add the block {time_scale: 'date', date_ranges: [{label: 'this is a date range', domain: ['2015-01-01', '2017-01-01']}]} the option I get on the drop down is "this is a date range"
- When I add the block {time_scale: 'day', day_range: [0,400]} the option I get on the drop down is "default"
- When I add the block {time_scale: 'day', day_ranges: [{label: 'this is a day range', domain: [0,400]}]} the option I get on the drop down is "this is a day range"
- When I alter start or end, the Time Range toggles to User Input

**Comment by samussiah** [comment]
@danedexF5 , those are the expected behaviors but I've gone back in and labeled `date_range/day_range` _Initial Date/Day Range_ to be more transparent.  When the _Start_/_End_ controls change the _Time range_ dropdown should change to _User Input_.

**Pull request merged**
