### PR TITLE
Time range control

### LINKED ISSUE #74: Add time range controls.
# Test notes
* A Start and End control appear in the controls section.
* The controls display a date set to the current time range.
* Given a date x-axis scale the controls display a date.
* Given a day x-axis scale the controls display a number.
* The controls accept text input and may contain up and down arrows that increment or decrement the time range.
* The Start control cannot be greater than the End control, and vice versa.

### PR DESCRIPTION
**Pull request by samussiah**
pre-refactor

# Issues
Closes #74

### CODE REVIEW

**Comment by dschwentker** [comment]
Time range controls are not working in IE 11. I get this error: 
"There might've been some problems initializing the chart. Errors include:
Error: Invalid argument."

The Start and End controls are blank boxes and the chart doesn't load at all.

**Comment by samussiah** [comment]
So IE doesn't support input[type=date].  The time range controls will just be free text fields in IE.  Ready for you again @dschwentker : 18500c20071b38ea60db128c8c7f697bd7ed15bc

**Comment by dschwentker** [comment]
This is actually working better in IE than it is in Firefox or Chrome now. In both of those browsers, when I switch to day for the x-axis scale, the Start and End fields are blank. The chart appears to show the default 1 to 375 day range, but the fields are blank. In Chrome, if I increment the End number by clicking the up arrow in the box, then suddenly the 1 and 375 numbers appear. If I increment the Start number, then Start is 1, but End becomes 2. I get somewhat similar behavior in Firefox, although when I increment wither Start or End, Start becomes 0 and End becomes 1.

Additionally, after I've switched to x-axis scale day, when I switch back to x-axis scale date, the date fields no longer show their previous values, they just display as mm/dd/yyyy in both the Start and End fields.

**Comment by dschwentker** [comment]
Tested and passed in all browsers using f892a107e08df98e396fff57a21bd90c351c76e7.

**Pull request merged**
