### PR TITLE
Data export

### LINKED ISSUE #124: Expose timelines data.
Request from DAIT.

# Test notes
* A _⇓ Data_ button is displayed in the population details container.
* The button exports the currently filtered data to .csv with one record per ID per event.

### LINKED ISSUE #139: Update settings merge process
Use the Results over Time as a prototype to update the settings merge process

# Test notes
* Testing not required.  Development updates do not affect the renderer.

### LINKED ISSUE #142: Make back button more apparent.
LG request.

# Test notes
* You can't stop staring at the back button in the ID timeline view.

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #124 
Closes #139 
Closes #142

### CODE REVIEW

**Comment by samussiah** [comment]
How do you mean @pburnsdata ?  The export should match the currently displayed data, like it should take  into account the time range, the selected event types, and the current filters.

**Comment by pburnsdata** [comment]
@samussiah Yeah, honestly I couldn't replicate what I was seeing earlier for a while, but realized I had opened CAT in IE when I did this so went back to IE and there did seem to be some wonkiness. Might just be an IE thing...
event type in csv output not matching filters

**Comment by pburnsdata** [comment]
@samussiah To reproduce: in IE render the chart, export csv, change the filters, click export csv again, and your second csv will still have the filters from the first. Seems to only happen in IE

**Comment by samussiah** [comment]
Nice catch @pburnsdata Preston.  Should be fixed.

**Pull request merged**
